@startuml
class Rector {
    + RectorID : int <<get>> <<set>>
    + <<required>> FirstName : string <<get>> <<set>>
    + <<required>> LastName : string <<get>> <<set>>
    + <<required>> ContactNumber : string <<get>> <<set>>
}
User <|-- Rector
Rector --> "Gender" Gender
@enduml
